[font]
size = 18.0

[font.normal]
family = "Iosevka Fixed"
style = "Regular"

[window.padding]
x = 10
y = 10

[terminal.shell]
program = "/usr/bin/fish"

[mouse]
hide_when_typing = true

[general]
import = [
   "~/.config/alacritty/gruvbox-light.toml"
]

[terminal]

