[colors.primary]
background = "#fbf1c7"
foreground = "#3c3836"
dim_foreground = "#7c6f64"
bright_foreground = "#3c3836"

[colors.cursor]
text = "#fbf1c7"
cursor = "#9d0006"

[colors.vi_mode_cursor]
text = "#fbf1c7"
cursor = "#076678"

[colors.search.matches]
foreground = "#fbf1c7"
background = "#665c54"

[colors.search.focused_match]
foreground = "#fbf1c7"
background = "#79740e"

[colors.footer_bar]
foreground = "#fbf1c7"
background = "#665c54"

[colors.hints.start]
foreground = "#fbf1c7"
background = "#b57614"

[colors.hints.end]
foreground = "#fbf1c7"
background = "#665c54"

[colors.selection]
text = "#fbf1c7"
background = "#9d0006"

[colors.normal]
black = "#928374"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#3c3836"

[colors.bright]
black = "#a89984"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#504945"

[[colors.indexed_colors]]
index = 16
color = "#af3a03"

[[colors.indexed_colors]]
index = 17
color = "#d65d0e"
