format = '$directory$git_branch$git_status$python$line_break$character'

add_newline = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✖](bold red)'

[python]
format = '[(\($virtualenv\))]($style)'

