theme = "catppuccin_mocha_transparent"

[editor]
line-number = "relative"
completion-timeout = 5
auto-info = false
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
g = { c = ":bc!" }
