[[language]]
name = "verilog"
file-types = ["vh", "sv", "svh"]

[[language]]
name = "html"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
"'" = "'"
'"' = '"'
'`' = '`'
'<' = '>'

[[language]]
name = "jakt"
scope = "source.jakt"
injection-regex = "jakt"
file-types = ["jakt"]
comment-tokens = "//"
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "jakt"
source = { git = "https://github.com/SerenityOS/tree-sitter-jakt", rev = "e67a5de093cab9eb79be721bf39bc9115193534a" }
