[[language]]
name = "hare"
indent = { tab-width = 3, unit = "   " }

[[language]]
name = "css"
indent = { tab-width = 3, unit = "   " }

[[language]]
name = "python"
auto-format = true

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "c"
indent = { tab-width = 3, unit = "   " }

[[language]]
name = "soba"
scope = "source.soba"
file-types = ["soba"]
comment-token = "\\"
indent = { tab-width = 3, unit = "   " }

[[grammar]]
name = "soba"
source = { path = "/home/hugo/projects/tree-sitter-soba" }
