#!/usr/bin/env bash

export PATH="$HOME/.config/bspwm/scripts:$PATH"
export XDG_CURRENT_DESKTOP="bspwm"

export _JAVA_AWT_WM_NONREPARENTING=1

default_workspaces() {
    for monitor in `xrandr -q | grep -w 'connected' | cut -d' ' -f1`; do
        bspc monitor "$monitor" -d '' '' '' '' '' '' '' ''
    done
}

two_monitors_workspaces() {
    INTERNAL_MONITOR="eDP"
    EXTERNAL_MONITOR="HDMI-A-0"
    if [[ $(xrandr -q | grep "$EXTERNAL_MONITOR connected") ]]; then
        bspc monitor "$EXTERNAL_MONITOR" -d '' '' '' ''
        bspc monitor "$INTERNAL_MONITOR" -d '' '' '' ''
        bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
    else
        bspc monitor "$INTERNAL_MONITOR" -d '' '' '' '' '' '' '' ''
    fi
}

three_monitors_workspaces() {
    MONITOR_1='eDP'
    MONITOR_2='HDMI-A-0'
    MONITOR_3='HDMI-A-1'
    bspc monitor "$MONITOR_1" -d '' ''
    bspc monitor "$MONITOR_2" -d '' '' ''
    bspc monitor "$MONITOR_3" -d '' '' ''
    bspc wm -O "$MONITOR_2" "$MONITOR_1" "$MONITOR_3"
}

default_workspaces
#two_monitors_workspaces
#three_monitors_workspaces

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color '#81A1C1'
bspc config normal_border_color '#2E3440'
bspc config active_border_color '#B48EAD'
bspc config presel_feedback_color '#A3BE8C'

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config presel_feedback true

bspc wm --adopt-orphans

declare -a floating=(alacritty-float Thunar Yad 'Firefox:Places' Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

killall -9 sxhkd dunst xfce4-power-manager mpd

sxhkd &

xfce4-power-manager &

xsetroot -cursor_name left_ptr

feh --bg-fill "$HOME/Pictures/Wallpapers/nord.jpg"

exec mpd &

bspbar
bspcomp
bspdunst
