#!/usr/bin/env bash

get_backlight() {
    echo "$(brightnessctl | grep -oP '\(\K\d+(?=%\))')"
}

get_icon() {
    current="$(get_backlight)"
    if [[ ("$current" -ge "0") && ("$current" -le "20") ]]; then
        icon="$HOME/.config/dunst/icons/brightness-20.png"
    elif [[ ("$current" -ge "20") && ("$current" -le "40") ]]; then
        icon="$HOME/.config/dunst/icons/brightness-40.png"
    elif [[ ("$current" -ge "40") && ("$current" -le "60") ]]; then
        icon="$HOME/.config/dunst/icons/brightness-60.png"
    elif [[ ("$current" -ge "60") && ("$current" -le "80") ]]; then
        icon="$HOME/.config/dunst/icons/brightness-80.png"
    elif [[ ("$current" -ge "80") && ("$current" -le "100") ]]; then
        icon="$HOME/.config/dunst/icons/brightness-100.png"
    fi
}

notify_user() {
    get_icon && dunstify -u low -h string:x-dunst-stack-tag:obbacklight -i "$icon" "Brightness : $(get_backlight)%"
}

inc_backlight() {
    brightnessctl set 5%+ && notify_user
}

dec_backlight() {
    brightnessctl set 5%- && notify_user
}

if [[ "$1" == '--get' ]]; then
    get_backlight
elif [[ "$1" == '--inc' ]]; then
    inc_backlight
elif [[ "$1" == '--dec' ]]; then
    dec_backlight
else
    get_backlight
fi
