#!/usr/bin/env bash

get_backlight() {
    echo "$(brightnessctl | grep -oP '\(\K\d+(?=%\))')"
}

notify_user() {
    dunstify -u low -h string:x-dunst-stack-tag:obbacklight "Brightness : $(get_backlight)%"
}

inc_backlight() {
    brightnessctl set 5%+ && notify_user
}

dec_backlight() {
    brightnessctl set 5%- && notify_user
}

if [[ "$1" == '--get' ]]; then
    get_backlight
elif [[ "$1" == '--inc' ]]; then
    inc_backlight
elif [[ "$1" == '--dec' ]]; then
    dec_backlight
else
    get_backlight
fi
