#!/usr/bin/env bash

if [ "$1" == "--float" ]; then
    alacritty --class 'alacritty-float,alacritty-float'
elif [ "$1" == "--full" ]; then
    alacritty --class 'alacritty-fullscreen,alacritty-fullscreen' \
              -o window.startup_mode="'Fullscreen'" \
                 window.padding.x=30 window.padding.y=30 \
                 window.opacity=0.95 font.size=14
else
    alacritty ${@}
fi
