colorscheme catppuccin_mocha

add-highlighter -override global/line_numbers number-lines -relative -hlcursor
add-highlighter -override global/matching_pairs show-matching -previous

set-option global autoreload true
set-option global scrolloff 3,3

nop %sh{
    mkdir -p "$kak_config/autoload"
    ln -s "$kak_runtime/autoload" "$kak_config/autoload/stdlib"
}

hook global BufOpenFile .* %{ editorconfig-load }
hook global BufNewFile .* %{ editorconfig-load }

try %{ declare-user-mode make-mode }
try %{ declare-user-mode kak-config-mode }

map global -docstring "format buffer" user '=' ":format<ret>"
map global -docstring "find file" user 'f' ":pick-file<ret>"
map global -docstring "find buffer" user 'b' ":buffer "

map global -docstring "make" user 'm' ":enter-user-mode make-mode<ret>"
map global -docstring "kak config" user 'k' ":enter-user-mode kak-config-mode<ret>"

map global -docstring "next" make-mode 'n' ":make-next-error<ret>"
map global -docstring "previous" make-mode 'p' ":make-previous-error<ret>"
map global -docstring "make" make-mode 'm' ":make<ret>"

map global -docstring "edit" kak-config-mode 'e' ":edit '%val{config}/kakrc'<ret>"
map global -docstring "source" kak-config-mode 's' ":source '%val{config}/kakrc'<ret>"

define-command pick-file -override %{
    prompt -menu -shell-script-candidates %{ fd -t f } 'File: ' %{ edit -- %val{text} }
}

hook global BufSetOption filetype=markdown %{
    set-option buffer autowrap_column 100

    map buffer normal <s-ret> ":markdown-toggle-checkbox<ret>"

    autowrap-enable
}

define-command markdown-toggle-checkbox -override -docstring "Toggle a markdown checkbox" %{
    try %{
        execute-keys -draft x 1s '\[( )\]'<ret> r x
    } catch %{
        try %{
            execute-keys -draft x 1s '\[(x)\]'<ret> r <space>
        } catch %{
        }
    }
}

hook global BufSetOption filetype=kak %{
    set-option buffer formatcmd "kakfmt"
}

hook global BufSetOption filetype=rust %{
    set-option buffer formatcmd "rustfmt"
}
