set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g set-clipboard on

unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

bind -n M-left select-pane -L
bind -n M-down select-pane -D
bind -n M-up select-pane -U
bind -n M-right select-pane -R

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n M-&  select-window -t 1
bind -n M-é  select-window -t 2
bind -n M-\" select-window -t 3
bind -n M-\' select-window -t 4
bind -n M-(  select-window -t 5
bind -n M--  select-window -t 6
bind -n M-è  select-window -t 7
bind -n M-_  select-window -t 8
bind -n M-ç  select-window -t 9

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g @ctp_bg "#24273a"
set -g @ctp_surface_1 "#494d64"
set -g @ctp_fg "#cad3f5"
set -g @ctp_pink "#f5c2e7"
set -g @ctp_lavender "#b4befe"
set -g @ctp_crust "#181926"

set -gF status-style "bg=#{@ctp_bg},fg=#{@ctp_fg}"

set -gF window-status-format "#[bg=#{@ctp_surface_1},fg=#{@ctp_fg}] ##I ##T "
set -gF window-status-current-format "#[bg=#{@ctp_pink},fg=#{@ctp_crust}] ##I ##T "

set -gF status-right " #[fg=#{@ctp_lavender}]##W #[bg=#{@ctp_lavender},fg=#{@ctp_crust}] ##S "
set -g status-left ""

